"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Review = { id: string; client_id: string; document_type: string; status: string; submitted_at: string };
type Profile = { id: string; first_name: string | null; last_name: string | null; country_code: string | null };

export default function VerificationReviewPage() {
  const [reviews, setReviews] = useState<Review[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [message, setMessage] = useState("Loading verification queue…"); const [busy, setBusy] = useState(false);
  const load = async () => { const supabase = createClient(); const [reviewResult, profileResult] = await Promise.all([supabase.from("identity_verifications").select("id, client_id, document_type, status, submitted_at").order("submitted_at", { ascending: false }), supabase.from("profiles").select("id, first_name, last_name, country_code")]); const error = reviewResult.error ?? profileResult.error; if (error) { setMessage(error.message); return; } setReviews((reviewResult.data ?? []) as Review[]); setProfiles((profileResult.data ?? []) as Profile[]); setMessage(""); };
  useEffect(() => { void load(); }, []);
  const review = async (item: Review, status: "approved" | "rejected") => { setBusy(true); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("identity_verifications").update({ status, reviewer_id: user?.id, reviewed_at: new Date().toISOString() }).eq("id", item.id); if (!error) { await supabase.from("profiles").update({ identity_status: status }).eq("id", item.client_id); await supabase.from("audit_events").insert({ actor_id: user?.id, entity_type: "identity_verification", entity_id: item.id, event_type: `verification_${status}`, metadata: { client_id: item.client_id } }); } setBusy(false); if (error) { setMessage(error.message); return; } setMessage(`Verification ${status}.`); await load(); };
  return <main className="signin-page"><Link href="/admin" className="brand"><span className="brand-mark">BW</span> Better Wealth</Link><section className="signin-card signup-card"><p className="eyebrow">Internal operations</p><h1>Verification queue.</h1><p>Review submitted files in the private KYC bucket before approving withdrawal eligibility. Confirm documents using your approved compliance process outside this screen.</p>{message && <p className="signin-message" role="status">{message}</p>}<div className="admin-table">{reviews.length ? reviews.map((item) => { const profile = profiles.find((entry) => entry.id === item.client_id); return <div className="admin-table-row" key={item.id}><div><strong>{[profile?.first_name, profile?.last_name].filter(Boolean).join(" ") || "Unnamed client"}</strong><small>{profile?.country_code || "Country not provided"}</small></div><span>{item.document_type.replace("_", " ")}</span><span>{item.status}</span><span className="admin-review-actions"><button disabled={busy} onClick={() => review(item, "approved")}>Approve</button><button disabled={busy} onClick={() => review(item, "rejected")}>Reject</button></span></div>; }) : <p>No verification submissions yet.</p>}</div><div className="signin-links"><Link href="/admin">Back to admin</Link><Link href="/portal/verification">Client upload page</Link></div></section></main>;
}
