import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";

const instruments = [["Bitcoin", "BTC / USD", "$67,420.00", "+2.18%", "up"], ["Ethereum", "ETH / USD", "$3,512.00", "−0.64%", "down"], ["Gold spot", "XAU / USD", "$2,384.10", "+0.91%", "up"], ["S&P 500", "SPX", "5,612.40", "+0.44%", "up"]];
const services = [["01", "Global markets", "A considered view across listed securities, major indices, commodities, and selected digital assets."], ["02", "Client reporting", "A single private portal for portfolio value, holdings, documents, and account activity."], ["03", "Operational care", "Important funding and verification actions follow a clear, human-led review process."]];
const plans = [["Foundation", "$250", "A clear starting point for investors building a long-term plan."], ["Growth", "$2,500", "Broader multi-asset exposure and a more detailed client reporting experience."], ["Private", "$10,000", "A tailored relationship for clients with more complex needs and larger portfolios."]];

export default function Home() {
  return <main className="institutional-home">
    <section className="ih-hero">
      <nav className="ih-nav" aria-label="Primary navigation"><Link href="/" className="brand brand-home"><BrandLogo inverse /></Link><div className="ih-links"><a href="#markets">Markets</a><a href="#services">Our approach</a><a href="#plans">Investment plans</a></div><Link href="/sign-in" className="ih-login">Client sign in <span>↗</span></Link></nav>
      <div className="ih-hero-copy"><p className="ih-kicker">Better Wealth Investment Group · 2026</p><h1>Invest with a<br /><em>clearer view.</em></h1><p>Global investment access and a considered private-client experience, brought together in one place.</p><div><a className="ih-primary" href="#plans">Discover Better Wealth <span>↓</span></a><a className="ih-text-link" href="#markets">View markets <span>↗</span></a></div></div>
      <div className="ih-hero-foot"><span>Independent client experience</span><span>Capital is at risk</span><span>Scroll to explore <b>↓</b></span></div>
    </section>
    <section className="ih-intro"><p className="ih-kicker">Our point of view</p><div><h2>A more composed way to stay close to your wealth.</h2><p>We believe investment information should be useful without becoming overwhelming. Our digital experience is designed around the moments that matter: understanding your position, making a request, and having a clear next step.</p></div></section>
    <section id="markets" className="ih-markets"><header><div><p className="ih-kicker">Market watch</p><h2>A view across<br />the <em>investment landscape.</em></h2></div><p>Indicative market information is presented alongside the service experience. It is not investment advice.</p></header><div className="ih-price-grid">{instruments.map(([name, symbol, price, move, direction], index) => <article key={symbol}><span>0{index + 1}</span><div><p>{name}</p><small>{symbol}</small></div><strong>{price}</strong><b className={direction === "up" ? "ih-up" : "ih-down"}>{direction === "up" ? "▲" : "▼"} {move}</b></article>)}</div><a href="#plans" className="ih-arrow-link">Explore investment options <span>→</span></a></section>
    <section id="services" className="ih-services"><div className="ih-services-art"><span>BW</span><i /><i /><i /></div><div className="ih-services-copy"><p className="ih-kicker">Designed around the client</p><h2>Precision in the details. Calm in the experience.</h2><p>Every part of the client portal has a practical job to do. The result is a service that feels more deliberate, easier to understand, and ready when it is needed.</p><div className="ih-service-list">{services.map(([number, title, copy]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div><b>↗</b></article>)}</div></div></section>
    <section className="ih-portal"><div><p className="ih-kicker">Your private view</p><h2>Everything essential,<br /><em>in its place.</em></h2><p>From a portfolio’s current valuation to an in-progress funding request, the Better Wealth client portal is designed to make the next action clear.</p><Link href="/sign-in" className="ih-text-link">Enter client portal <span>↗</span></Link></div><div className="ih-portal-frame" aria-label="Illustrative client portal preview"><div className="ih-frame-bar"><span className="ih-frame-logo">BW</span><i /><i /><i /></div><div className="ih-frame-body"><p>Client portfolio</p><strong>$84,206.19</strong><b>+4.80% <small>over the current period</small></b><div className="ih-frame-chart"><svg viewBox="0 0 500 150" preserveAspectRatio="none" aria-hidden="true"><path d="M0 126 C47 109 66 118 101 95 S163 107 196 73 S255 90 290 51 S344 74 378 43 S444 48 500 7" /></svg></div><div className="ih-frame-summary"><span>Global portfolio <b>48%</b></span><span>Digital assets <b>31%</b></span><span>Alternatives <b>21%</b></span></div></div></div></section>
    <section id="plans" className="ih-plans"><header><p className="ih-kicker">Investment plans</p><h2>A service that can<br />meet you where you are.</h2></header><div>{plans.map(([name, minimum, copy], index) => <article key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{copy}</p><div><small>Indicative minimum</small><strong>{minimum}</strong></div><a href="#contact">Discuss this plan <b>→</b></a></article>)}</div><p className="ih-disclaimer">Plan suitability, fees, minimums, availability, and risk disclosures require approval before publication.</p></section>
    <section className="ih-quote"><p>“A financial relationship should feel informed, personal, and built for the long term.”</p><span>Better Wealth Investment Group</span></section>
    <section id="contact" className="ih-contact"><p className="ih-kicker">Begin a conversation</p><h2>Build a clearer<br /><em>next chapter.</em></h2><p>Speak with Better Wealth about the service and approach that may be appropriate for you.</p><a href="mailto:hello@betterwealth.example" className="ih-primary">Contact Better Wealth <span>↗</span></a></section>
    <footer className="ih-footer"><Link href="/" className="brand brand-home"><BrandLogo inverse /></Link><div><a href="#markets">Markets</a><a href="#services">Our approach</a><a href="#plans">Investment plans</a><Link href="/sign-in">Client portal</Link></div><p>© 2026 Better Wealth Investment Group.<br />Capital is at risk. This site is not investment advice.</p></footer>
  </main>;
}
