import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";
import { MarketTicker } from "@/components/market-ticker";

const instruments = [["Bitcoin", "BTC / USD", "$67,420.00", "+2.18%", "up"], ["Ethereum", "ETH / USD", "$3,512.00", "−0.64%", "down"], ["Gold spot", "XAU / USD", "$2,384.10", "+0.91%", "up"], ["S&P 500", "SPX", "5,612.40", "+0.44%", "up"]];
const services = [["01", "Global markets", "A considered view across listed securities, major indices, commodities, and selected digital assets."], ["02", "Client reporting", "A single private portal for portfolio value, holdings, documents, and account activity."], ["03", "Operational care", "Important funding and verification actions follow a clear, human-led review process."]];
const plans: Array<{ name: string; minimum: string; description: string; features: string[] }> = [{ name: "Foundation", minimum: "$250", description: "A clear starting point for investors building a long-term plan.", features: ["Stocks & ETFs", "Crypto access", "Portfolio reporting", "Client support"] }, { name: "Growth", minimum: "$2,500", description: "A broader multi-asset allocation for investors seeking a more active portfolio experience.", features: ["Stocks, ETFs & indices", "Crypto access", "Enhanced reporting", "Priority support"] }, { name: "Private", minimum: "$10,000", description: "A tailored relationship for larger portfolios and more complex investment requirements.", features: ["Multi-asset portfolio", "Digital assets & commodities", "Advanced reporting", "Priority account support"] }];

export default function Home() {
  return <main className="institutional-home">
    <section className="ih-hero">
      <nav className="ih-nav" aria-label="Primary navigation"><Link href="/" className="brand brand-home"><BrandLogo inverse /></Link><div className="ih-links"><a href="#markets">Markets</a><a href="#services">Our approach</a><a href="#plans">Investment plans</a></div><Link href="/sign-in" className="ih-login">Client sign in <span>↗</span></Link></nav>
      <div className="ih-hero-copy"><p className="ih-kicker">Better Wealth Investment Group · 2026</p><h1>Invest with a<br /><em>clearer view.</em></h1><p>Global investment access and a considered private-client experience, brought together in one place.</p><div><a className="ih-primary" href="#plans">Discover Better Wealth <span>↓</span></a><a className="ih-text-link" href="#markets">View markets <span>↗</span></a></div></div>
      <div className="ih-moon-stage" aria-hidden="true"><span className="ih-rising-moon" /><i /><i /><i /></div>
      <div className="ih-hero-foot"><span>Independent client experience</span><span>Capital is at risk</span><span>Scroll to explore <b>↓</b></span></div>
    </section>
    <MarketTicker />
    <section className="company-stats"><p>Capital is at risk. Investment values can rise and fall.</p><div><article><strong>4.5M+</strong><span>Client accounts</span></article><article><strong>145+</strong><span>Countries served</span></article><article><strong>$27.9B</strong><span>Assets managed</span></article><article><strong>October 2010</strong><span>Founded</span></article></div></section>
    <section className="ih-intro"><p className="ih-kicker">Our point of view</p><div><h2>A more composed way to stay close to your wealth.</h2><p>We believe investment information should be useful without becoming overwhelming. Our digital experience is designed around the moments that matter: understanding your position, making a request, and having a clear next step.</p></div></section>
    <section id="markets" className="ih-markets"><header><div><p className="ih-kicker">Market watch</p><h2>A view across<br />the <em>investment landscape.</em></h2></div><p>Indicative market information is presented alongside the service experience. It is not investment advice.</p></header><div className="ih-price-grid">{instruments.map(([name, symbol, price, move, direction], index) => <article key={symbol}><span>0{index + 1}</span><div><p>{name}</p><small>{symbol}</small></div><strong>{price}</strong><b className={direction === "up" ? "ih-up" : "ih-down"}>{direction === "up" ? "▲" : "▼"} {move}</b></article>)}</div><a href="#plans" className="ih-arrow-link">Explore investment options <span>→</span></a></section>
    <section id="services" className="ih-services"><div className="ih-services-art"><span>BW</span><i /><i /><i /></div><div className="ih-services-copy"><p className="ih-kicker">Designed around the client</p><h2>Precision in the details. Calm in the experience.</h2><p>Every part of the client portal has a practical job to do. The result is a service that feels more deliberate, easier to understand, and ready when it is needed.</p><div className="ih-service-list">{services.map(([number, title, copy]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div><b>↗</b></article>)}</div></div></section>
    <section className="ih-portal"><div><p className="ih-kicker">Your private view</p><h2>Everything essential,<br /><em>in its place.</em></h2><p>From a portfolio’s current valuation to an in-progress funding request, the Better Wealth client portal is designed to make the next action clear.</p><Link href="/sign-in" className="ih-text-link">Enter client portal <span>↗</span></Link></div><div className="client-portfolio-preview" aria-label="Illustrative client portfolio preview"><header><span>CLIENT PORTAL</span><b>Portfolio overview</b><i>Private client</i></header><div className="client-value"><small>Portfolio value</small><strong>$84,206.19</strong><span>▲ 4.80% <i>This month</i></span></div><div className="client-holdings"><p>Current holdings</p><span><i className="asset-one" />Global equity portfolio <b>$40,419.00</b></span><span><i className="asset-two" />Bitcoin <b>$26,104.00</b></span><span><i className="asset-three" />Gold spot <b>$17,683.19</b></span></div></div></section>
    <section id="plans" className="ih-plans"><header><p className="ih-kicker">Investment plans</p><h2>Choose a plan built around your goals.</h2><p>Pick a comfortable portfolio tier during sign-up. Your selected plan follows you into your Better Wealth dashboard.</p></header><div className="plan-card-grid">{plans.map(({ name, minimum, description, features }, index) => <article className={index === 1 ? "plan-selected" : ""} key={name}><div className="plan-card-label"><span>{index === 1 ? "Most popular" : index === 0 ? "Balanced" : "Advanced"}</span><small>0{index + 1}</small></div><h3>{name}</h3><p>{description}</p><div className="plan-minimum"><small>Minimum</small><strong>{minimum}</strong></div><ul>{features.map((feature) => <li key={feature}>✓ {feature}</li>)}</ul><a href="#contact">Choose {name} <b>→</b></a></article>)}</div><p className="ih-disclaimer">Plan suitability, fees, minimums, availability, and risk disclosures require approval before publication.</p></section>
    <section className="ih-quote"><p>“A financial relationship should feel informed, personal, and built for the long term.”</p><span>Better Wealth Investment Group</span></section>
    <section id="contact" className="ih-contact"><p className="ih-kicker">Begin a conversation</p><h2>Ready to put your<br /><em>capital to work?</em></h2><p>Open an account in minutes, or speak with Better Wealth about the next appropriate step.</p><div><Link href="/create-account" className="ih-primary">Create account <span>↗</span></Link><a href="mailto:hello@betterwealth.example" className="ih-secondary">Talk to an advisor</a></div></section>
    <footer className="ih-footer"><Link href="/" className="brand brand-home"><BrandLogo inverse /></Link><div><a href="#markets">Markets</a><a href="#services">Our approach</a><a href="#plans">Investment plans</a><Link href="/sign-in">Client portal</Link></div><p>© 2026 Better Wealth Investment Group.<br />Capital is at risk. This site is not investment advice.</p></footer>
  </main>;
}
